server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
- job_name: my-container-logs
  static_configs:
  - targets: # tells promtail to look for the logs on the current machine/host
      - localhost
    labels: # labels with which all the following logs should be labelled
      job: my-container  # label-1
      host: main-host   # label-2
      __path__: /var/lib/docker/containers/01850dd06f90*/01850dd06f90*-json.log
